### ISSUE TITLE
Create DB Context and Models

### ISSUE THREAD

**Issue by dortlii** [zbw-lori/lori-backend#14]

**Comment by dortlii** [comment]
Models are updated with foreign keys

**Comment by faesslerm** [comment]
Kurze Frage... Müssten die Models wie z.B. Address, Robot, etc. nicht ins Package lori.backend.Core?

**Comment by dortlii** [comment]
Hm... wäre Business Logik - ich verschiebs heute am Abend ins Core-Projekt. Merci für den Hinweis!
