### ISSUE TITLE
Model Route anpassen

### ISSUE THREAD

**Issue by dortlii** [zbw-lori/lori-backend#50]
Gemäss Figma

**Comment by faesslerm** [comment]
@dortlii Habe nun die branches auf develop gemerged. Der branch feature/mqtt ist unabhängig von den Models, weswegen ich auf diesem die restlichen MQTT Sachen einchecken werde. Du kannst somit die Models anpassen. 😄

**Comment by dortlii** [comment]
@faesslerm - hast Du mir noch den Link zum aktuellsten Figma? Meins ist schon älter:

https://www.figma.com/file/zzXPUs5nIW8ODHWAOqidXp/LORI_ERM?type=whiteboard&node-id=0%3A1&t=DugcrP7taf5TJEAJ-1

<img width="307" alt="image" src="https://github.com/zbw-lori/lori-backend/assets/22558338/66abe0f3-c77b-45b7-838f-960034f86343">

**Comment by faesslerm** [comment]
ja klar - https://www.figma.com/file/3B063kxm6k2Kozfz6feror/LORI_ERM?type=whiteboard&t=yBZkJ8WXZimCongB-1
