### ISSUE TITLE
Create Database ERM

### ISSUE THREAD

**Issue by faesslerm** [zbw-lori/lori-backend#9]
ERM with more details, like Primary-/Foreign Keys and also some additional fields.
Do we store livedata of the roboter persistent (database) or in-memory?

**Comment by faesslerm** [comment]
Kannst du hier noch den Link zum Figma teilen?

**Comment by dortlii** [comment]
Figma File: [LORI_ERM.jam](https://github.com/zbw-lori/lori-docs/blob/main/LORI_ERM.jam)

**Comment by faesslerm** [comment]
Frage .... Die Tabelle Route hat ein Feld "priority_list" was vom Typ JSON ist.
Was waren deine Gedanken diesbezüglich bzw. was für ein Inhalt erwartest du?

**Comment by dortlii** [comment]
Stand so in einer Folie und google spuckte den EF Type raus. Keine Gedanken, reines umsetzen 🤣
